name: Deploy Preview
on: 
  pull_request:
    branches:
      - master

jobs:
  build:
    # 2. Using the latest Ubuntu image
    runs-on: ubuntu-latest

    steps:
      # Check out the current repository code
      - uses: actions/checkout@v1
      # Setup python 3.7
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      # Install pipenv
      - uses: dschep/install-pipenv-action@v1
      # 3. https://github.com/actions/setup-node#usage
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      # This triggers `docusaurus build` script in "package.json"
      - run: npm run build
      # 4. Deploy the docusaurus build to Netlify
      - uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          # 5. "docusaurus build" creates "public" folder, which is what we are deploying
          args: deploy --dir=build --prod --alias deploy-preview-${{ github.event.number }}
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
